# Generated by Django 2.2 on 2019-05-03 07:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190503_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.TextField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
