# Generated by Django 2.2 on 2019-05-03 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190503_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
