# Generated by Django 2.2 on 2019-05-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
