# Generated by Django 2.2 on 2019-05-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
        ('blog', '0015_delete_like'),
    ]

    operations = [
    ]
