# Generated by Django 2.2 on 2019-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_merge_20190503_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='_post_likes_+', to='blog.Post'),
        ),
    ]
